language: C
sudo: required
dist: trusty
compiler:
  - gcc
before_install:
  - uname -a
  - sudo apt-get update 
  - sudo apt-get install -y -qq build-essential cmake gfortran 
script:
  - mkdir build
  - cd build
  - cmake -G"Unix Makefiles" ../
  - make build_tests install
  - cd ..
  - ./test/bin/uparser_test
  - ./test/bin/uparser_test_fortran
